#!/bin/bash
#
# kasutaja tervitus
#
# skripti algus
#
#echo -n "Tere User !"
echo -n "Tere"
echo -n ` who am i | cut -c1 | tr [:lower:] [:upper:]` # loika esimene taht ja muuda suureks
echo -n `who am i | cut -c2-` # loika koik tahed alatest 2-st
echo "!"
#
# sktripti lopp
