#!/bin/bash
#
# kasutajte nimekiri kujul perenimi, eesnimi
#
# skripri algus
#
who | cut -f1 -d" " | cut -f2 -d"." > perenimi
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi
paste -d"." perenimi eesnimi > nimed
awk  {print} nimed | sort
#
# skriptimise lopp

